language: python
python:
  - "3.8"
sudo: required

services:
  - docker

before_install:
  - docker build -t nicocarratala/ahorcadopy -f Dockerfile .

script:
  - docker run -e CI=true nicocarratala/ahorcadopy python -m unittest

after_success:
  - coverage run --omit '/*' -m unittest
  - coveralls
  - docker build -t nicocarratala/ahorcadopy .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push nicocarratala/ahorcadopy