language: python
python:
  - "3.8"
sudo: required
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python -m unittest
  - coverage run --omit '/home/travis/virtualenv/python3.8.0/lib/*' -m unittest
  - coveralls
after_success:
  - docker build -t nicocarratala/ahorcadopy .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push nicocarratala/ahorcadopy